apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wp-projeto
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: MTIzNDU2 #123456
  MYSQL_PASSWORD: MTIzNDU2 #123456
  MYSQL_ROOT_PASSWORD: MTIzNDU2 #123456